- name: Install all required python packages
  become: yes
  become_method: sudo
  become_user: root
  shell: |
    pip3 install urllib
    apt-get update
  args:
    warn: false

- name: Transfer crawler file
  template:
    src: review_crawler.py.j2
    dest: review_crawler.py

- name: Transfer crawler file
  template:
    src: run_crawler.sh.j2
    dest: run_crawler.sh

- name: Changing perm of "run_crawler.sh", adding "+x"
  file: dest=run_crawler.sh mode=a+x

- name: Execute the script
  command: sh run_crawler.sh