- name: Install all required python packages
  become: yes
  become_method: sudo
  become_user: root
  shell: |
    pip3 install urllib
    apt-get update
  args:
    warn: false

- name: Transfer crawler file
  template:
    src: review_crawler.py.j2
    dest: review_crawler.py

- name: Transfer crawler file
  template:
    src: run.sh.j2
    dest: run.sh

- name: Execute the script
  command: sh /home/test_user/test.sh/bin/forever start app.js